version: '3.7'
services:
  mythril:
    build:
      context: ./analyze_tool
      dockerfile: docker/mythril/Dockerfile
    expose:
      - "8084"
    environment:
      - TOOLNAME=Mythril
      - PORT=8084
    restart: on-failure
  manticore:
    build:
      context: ./analyze_tool
      dockerfile: docker/manticore/Dockerfile
    expose:
      - "8085"
    environment:
      - TOOLNAME=Manticore
      - PORT=8085
    restart: on-failure
  slither:
    build:
      context: ./analyze_tool
      dockerfile: docker/slither/Dockerfile
    expose:
      - "8086"
    environment:
      - TOOLNAME=Slither
      - PORT=8086
    restart: on-failure
  contract_analyzer:
    build:
      context: ./contract_analyzer
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - MYTHRILPORT=8084
      - MANTICOREPORT=8085
      - SLITHERPORT=8086
    restart: on-failure
    depends_on:
      - mongodb
      - mythril
      - slither
      - manticore
  mongodb:
    image: mongo:4.0.4
    ports:
      - "27017:27017"
    # expose:
    #   - "27017"  生产环境不需要暴露端口在宿主机上