// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: pb/scat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceCode string `protobuf:"bytes,1,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
}

func (x *SourceCodeRequest) Reset() {
	*x = SourceCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_scat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceCodeRequest) ProtoMessage() {}

func (x *SourceCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceCodeRequest.ProtoReflect.Descriptor instead.
func (*SourceCodeRequest) Descriptor() ([]byte, []int) {
	return file_pb_scat_proto_rawDescGZIP(), []int{0}
}

func (x *SourceCodeRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

type CheckResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reslut string `protobuf:"bytes,1,opt,name=reslut,proto3" json:"reslut,omitempty"`
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_scat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_pb_scat_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResult) GetReslut() string {
	if x != nil {
		return x.Reslut
	}
	return ""
}

var File_pb_scat_proto protoreflect.FileDescriptor

var file_pb_scat_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x73, 0x63, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x33, 0x0a, 0x11, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x6c, 0x75,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x6c, 0x75, 0x74, 0x32,
	0x52, 0x0a, 0x0c, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x12,
	0x42, 0x0a, 0x16, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_scat_proto_rawDescOnce sync.Once
	file_pb_scat_proto_rawDescData = file_pb_scat_proto_rawDesc
)

func file_pb_scat_proto_rawDescGZIP() []byte {
	file_pb_scat_proto_rawDescOnce.Do(func() {
		file_pb_scat_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_scat_proto_rawDescData)
	})
	return file_pb_scat_proto_rawDescData
}

var file_pb_scat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_scat_proto_goTypes = []interface{}{
	(*SourceCodeRequest)(nil), // 0: pb.SourceCodeRequest
	(*CheckResult)(nil),       // 1: pb.CheckResult
}
var file_pb_scat_proto_depIdxs = []int32{
	0, // 0: pb.AnalyzeTools.checkSmartContractCode:input_type -> pb.SourceCodeRequest
	1, // 1: pb.AnalyzeTools.checkSmartContractCode:output_type -> pb.CheckResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_scat_proto_init() }
func file_pb_scat_proto_init() {
	if File_pb_scat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_scat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_scat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_scat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_scat_proto_goTypes,
		DependencyIndexes: file_pb_scat_proto_depIdxs,
		MessageInfos:      file_pb_scat_proto_msgTypes,
	}.Build()
	File_pb_scat_proto = out.File
	file_pb_scat_proto_rawDesc = nil
	file_pb_scat_proto_goTypes = nil
	file_pb_scat_proto_depIdxs = nil
}
