# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release-scat

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'README.md'
      - 'LICENSE'
      - 'go.mod'
      - 'go.sum'
      - '.gitignore'
      - '.github/**'
      - 'Dockerfile'
      
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    - name: Check out code
      uses: actions/checkout@v2

    - name: Update dependencies
      run: |
        cd analyze_tool
        go mod tidy

        cd ../contract_analyzer
        go mod tidy

    - name: Build analyze_tool
      run: |
        cd analyze_tool
        go build -o build/main ./main.go

    - name: Build contract_analyzer
      run: |
        cd contract_analyzer
        go build -o build/main ./main.go

    - name: package release
      run: |
        mkdir -p release/analyze_tool/build
        mkdir -p release/contract_analyzer/build
        cp -r analyze_tool/build/main release/analyze_tool/build
        cp -r analyze_tool/docker release/analyze_tool
        cp -r contract_analyzer/build/main release/contract_analyzer/build
        cp -r contract_analyzer/Dockerfile release/contract_analyzer
        cp -r docker-compose.yml release
        tar -czvf release.tar.gz release
        
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.tar.gz
        tag_name: v1.1
        release_name: Release v1.1
        body: "scat"
      env:
        GITHUB_TOKEN: ${{ secrets.LLLL }}
